# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 60dd093732397ca04067f0a6513a4d90254ab8f5babc5dc7a503ebcf6f3fd614c3b8691920d83fb025b1c07acaec54d5a70397c2fd28ad3212f65235413767eb

test:
  secret_key_base: d8a6c79a7c1d724be96e660283b4afabdad578a373b5d6b0dd4f8fb7b90e24c952e92465fa5300194a409e13e8be2eddfb83b7b5b4f7f4b71ddad3b6f872ec39

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
